import { rupeesToPaise, type Coupon, type HeroSlide } from '@bobby/shared';

export const COUPONS: Coupon[] = [
  {
    id: 'coupon-welcome',
    code: 'WELCOME10',
    description: '10% off your first order',
    type: 'PERCENT',
    value: 10,
    minOrderPaise: rupeesToPaise(2000),
    maxDiscountPaise: rupeesToPaise(1500),
    usageLimit: null,
    usedCount: 214,
    startsAt: '2026-01-01T00:00:00.000Z',
    expiresAt: null,
    isActive: true,
  },
  {
    id: 'coupon-festive',
    code: 'FESTIVE15',
    description: '15% off the festive collection',
    type: 'PERCENT',
    value: 15,
    minOrderPaise: rupeesToPaise(5000),
    maxDiscountPaise: rupeesToPaise(3000),
    usageLimit: 500,
    usedCount: 87,
    startsAt: '2026-08-01T00:00:00.000Z',
    expiresAt: '2026-11-30T23:59:59.000Z',
    isActive: true,
  },
  {
    id: 'coupon-flat500',
    code: 'FLAT500',
    description: '₹500 off orders over ₹4,000',
    type: 'FLAT',
    value: rupeesToPaise(500),
    minOrderPaise: rupeesToPaise(4000),
    maxDiscountPaise: null,
    usageLimit: 1000,
    usedCount: 342,
    startsAt: '2026-01-01T00:00:00.000Z',
    expiresAt: null,
    isActive: true,
  },
  {
    id: 'coupon-expired',
    code: 'EID2026',
    description: '20% off for Eid',
    type: 'PERCENT',
    value: 20,
    minOrderPaise: rupeesToPaise(3000),
    maxDiscountPaise: rupeesToPaise(2500),
    usageLimit: null,
    usedCount: 631,
    startsAt: '2026-03-01T00:00:00.000Z',
    // Deliberately expired, so the "expired coupon" path is demonstrable.
    expiresAt: '2026-04-15T23:59:59.000Z',
    isActive: false,
  },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: 'hero-1',
    eyebrow: '20 Years of Legacy',
    headline: 'Timeless',
    headlineAccent: 'Elegance',
    subtext: 'Discover premium ethnic wear for every celebration',
    ctaLabel: 'Explore Collection',
    ctaHref: '/collections/womens',
    imageUrl: '/images/hero/hero-1.jpg',
    imageAlt: 'Model wearing a deep maroon embroidered anarkali in a chandelier-lit hall',
    position: 0,
    isActive: true,
  },
  {
    id: 'hero-2',
    eyebrow: 'The Wedding Edit',
    headline: 'For the',
    headlineAccent: 'Big Day',
    subtext: 'Hand-worked lehengas and bridal sets, made to be photographed',
    ctaLabel: 'Shop Wedding',
    ctaHref: '/collections/wedding',
    imageUrl: '/images/hero/hero-2.jpg',
    imageAlt: 'Bridal lehenga with hand zardozi work',
    position: 1,
    isActive: true,
  },
  {
    id: 'hero-3',
    eyebrow: 'Just Landed',
    headline: 'New',
    headlineAccent: 'Arrivals',
    subtext: 'The latest pieces to reach our Mira Road stores',
    ctaLabel: 'See What’s New',
    ctaHref: '/collections/new-arrivals',
    imageUrl: '/images/hero/hero-3.jpg',
    imageAlt: 'Festive ethnic wear collection display',
    position: 2,
    isActive: true,
  },
];
